site_name: Hacking History, Programming Digital Scholarship
theme_dir: theme
theme: null
site_url: https://hacking-history.readthedocs.io
site_description: This is the companion workbook for HIS4936 at the University of South Florida. Digital content created by David J. Thomas and the students of HIS4936 is open-source. We welcome contributions. This site is based upon the digital workbook of Shawn Graham.
site_author: David J. Thomas
copyright: 'Copyright &copy; 2016 <a href="mailto:dave.a.base@gmail.com">David J. Thomas</a>'
repo_url: https://github.com/thePortus/hacking-history/
repo_name: 'GitHub'
pages: 
- Home: 'index.md'
- Getting Started: 'getting_started.md'
- Data-Driven Toolkit: 'toolkit.md'
- Projects:
  - Power of the Presidents: 'projects/2016_fall/brown_zoromski/brown_zoromski.md'
  - Why Code?:  'projects/2016_fall/bruffet_harris/bruffet_harris.md'
  - Wikileaks and the 2016 Race: 'projects/2016_fall/buchholz_thieryung/buchholz_thieryung.md'
  - Battlefield Memorials: 'projects/2016_fall/croson/croson.md'
  - Nuclear Testing and the News: 'projects/2016_fall/donahue/donahue.md'
  # - Confederate Economics: 'projects/2016_fall/dulabone/dulabone.md'
  - Hacking Food Sustainability: 'projects/2016_fall/fort/fort.md'
  - Divinity and Imperial Cult: 'projects/2016_fall/johnson_zalman/johnson_zalman.md'
  - Ghostwriting H.P. Lovecraft: 'projects/2016_fall/julien/julien.md'