site_name: Hacking History, Programming Digital Scholarship
theme_dir: theme
theme: null
site_url: https://hacking-history.readthedocs.io
site_description: Digital content created by David J. Thomas and the students of HIS4936 is open-source. We welcome contributions. This site is based upon the digital workbook of Shawn Graham.
site_author: David Thomas
repo_url: https://github.com/thePortus/hacking-history/
extra_css: [supporting/style.css]
pages: 
- Home: 'index.md'
- Getting Started: 'getting_started.md'
- Data-Driven Toolkit: 'toolkit.md'
- Roles: 'roles.md'
- Schedule:
  - Assignments: 'schedule/assignments.md'
  - Lessons: 'schedule/lessons.md'
