site_name: HIS 4936 - Hacking History, Programming Digital Scholarship
theme: readthedocs
theme_dir: "theme"
site_url: https://hacking-history.readthedocs.io
site_description: Digital content created by David J. Thomas and the students of HIS4936 is open-source. We welcome contributions. This site is based upon the digital workbook of Shawn Graham.
site_author: David Thomas
repo_url: https://github.com/thePortus/hacking-history/
pages: 
- Home: 'index.md'
- Schedule: 'schedule.md'
- Toolkit: 'toolkit.md'

